# Archivo generado automáticamente. No editar manualmente.
credentials = {'usernames': {'JLINARESA': {'name': 'ABACO COLOMBIA AJUSTADORES INTERNACIONALES SAS',
                             'password': '$2b$12$ahL62vdnNH4XM4C5V37cK.N7gpRj9.CpxOcpQPM7lJ4v39JI/J22W'},
               'GPEDRAZA': {'name': 'ADVANTA COLOMBIA SAS',
                            'password': '$2b$12$1/zDn1YJSGFObhAl9ZuXt.1QYH1pjk7WFXTBQ5zD.AVxdzRncexC2'},
               'ACORTESS': {'name': 'AJUSCOL CONSULTORES SAS',
                            'password': '$2b$12$hZ8dQefLs.H7PSol9YOj4eLujSgMWEmeebsJWvDYP.JUnE3DwhbbW'},
               'JHERNANP': {'name': 'AJUSPAL AJUSTADORES DE SEGUROS LTDA',
                            'password': '$2b$12$XJ7DyoM6AVi1ypeL68G1MuzREH1mJN0vG.5kXINAbZSNQXswRLV/S'},
               'HVELASQUEZR': {'name': 'Ajustes Ríos Ltda',
                               'password': '$2b$12$KfQ3k4VRQ0MtWQHJFGC05uK5TR6PG270ct2dBh/hxXWrh4.BN6THG'},
               'GPIEDRAHITAV': {'name': 'AJUSTES PIEDRAHITA SAS',
                                'password': '$2b$12$X5yAtS.BBcQ9rIfBjcvqbefRR9CUffwx55unX.ukUjyiNFbIzTt.m'},
               'ABOHORQUEZR': {'name': 'ALIZON EUGENIA BOHORQUEZ RONDON',
                               'password': '$2b$12$Qzp6sqKFo.e8oIn77GgIRe4tvorLeCyS9HrPQ1ClaKyETzFaid4dC'},
               'AMUNOZ': {'name': 'AM AJUSTADORES SAS',
                          'password': '$2b$12$qLa8z3MtvzB2v57Wh164eO9C0MMvSF64g75JAa1usKPRK6JPcqS/y'},
               'AVENEGASR': {'name': 'ARMANDO VENEGAS R SAS',
                             'password': '$2b$12$suJwLOFWWvaHi0keOybwD.fW1E0ddGKb4Yd04DoUAhTezT3sp4pmy'},
               'CROSARIOC': {'name': 'ARQUIAJUSTES LTDA',
                             'password': '$2b$12$lY1gpjMXn9uj4KUqGYiTg.h/LWED3eGb0QME.V7MwAAYWrx9.Ncm.'},
               'MJARAMILLOJ': {'name': 'ARS SEGUROS LTDA',
                               'password': '$2b$12$SkOxv8XDmRfDnslS6UxyV.NkEBuu/JMxAmUpqvNB9gncOofmJE5Em'},
               'AOCAMPO': {'name': 'AVALORA GLOBAL LOSS ADJUSTERS COLOMBIA SAS',
                           'password': '$2b$12$P2HimQdo7.8Ipp3Xt86HBu7y5NZO7D.6rCGlVmFX68YjtgzmN0Tam'},
               'JCABANZOP': {'name': 'Cabanzo y Asociados SAS',
                             'password': '$2b$12$YEafBIpMX2YQg6eFp5wGSOocH6nOWVZC9fT7CKMssIHq5RURlumwa'},
               'MCASTIBLANCOR': {'name': 'Castiblanco Asociados',
                                 'password': '$2b$12$DjKXHy2n4Rm5/qO8uO708ucjCOrZxWqayNCKF56fpNcbrRRw1Ka/K'},
               'FRODRIGUEZM': {'name': 'CHARLES TAYLOR SAS',
                               'password': '$2b$12$hudjncCtlqPWTTLDEjrmyuwnVEubncY.xcgXmSS4dqxtVpD3OgdQK'},
               'JCAMARGOA': {'name': 'CLASS SAS',
                             'password': '$2b$12$wpy8BHsKA9YJFyJjVsx7refWqWfhmXVqlg5l0wBdt0tkqcpaNdTYW'},
               'JSERNAY': {'name': 'COLUMBUS',
                           'password': '$2b$12$leyg74fXTn3sOHdGt7DXfuSMBZ7Ua1PJwNNf1TU89MTnZzJ1nxHey'},
               'GLOAIZAP': {'name': 'Comercio Internacional',
                            'password': '$2b$12$pLTxrcVTtmyXMiE2VURUBOLNbwJjtwqINSlx7nM.0N2CZ2v6l86y.'},
               'AARIZAB': {'name': 'COMPAÑÍA DE INGENIERIA MECANICA ELECTRICA Y CIVIL CIMEC SAS',
                           'password': '$2b$12$bheoy1g0Z1ToFXl8rQVOoevYtzoEwYNuXIwELTH4FD2v2tX/R31hi'},
               'LZARATEC': {'name': 'CONPORTUARIO LTDA',
                            'password': '$2b$12$MqFsJxudfWEeT19O42t2bOrVJ.yGZxIWfFVSby9EIwF2XXtiEU.Wq'},
               'CPERICOR': {'name': 'CP CONSULTING SAS',
                            'password': '$2b$12$iQAur2ZK/EiJp0PyN/C.Zet9BEE8BYsWlthuTiB1peVVmtpS9aPr6'},
               'CDELGADOL': {'name': 'DELGADO LONDOÑO S.A.S.',
                             'password': '$2b$12$5.xnFUXD3ngpvbgzGZ6lZO5cC.FpMVyencwVA7tZKJlOH6ABjaf46'},
               'HHIDALGOB': {'name': 'DIAGNOSTICO Y DISEÑO INGENIERIA LTDA',
                             'password': '$2b$12$duRLlKq.6TJc.jKlVrkoFOLNNjfLwZcZeVSR0whoqdbgrpEX1XPQS'},
               'DGOMEZM': {'name': 'DIANA MARIA GOMEZ MOLINA',
                           'password': '$2b$12$q9TqUDC05Vs1do.2VDWHMu6Usi6dP4PZS/FWbWJNwDJRg.MQ8d/3u'},
               'EINSUASTYB': {'name': 'E. INSUASTY AJUSTADORES ASOCIADOS SAS',
                              'password': '$2b$12$HKE4oYQtmdRRWhJvPwxIgekDSdt9Nyv.kBIDQ14qLV9MLo3I/pNMm'},
               'LTORRESC': {'name': 'ENLACE AJUSTADORES DE SEGUROS S.A.S.',
                            'password': '$2b$12$G2DFoQEgj90x8c7Mr409headh/Eh/YX/pUdqlQmmdRENXRd9I2rQW'},
               'FOLIVEROS': {'name': 'Fabián Oliveros Bustamante',
                             'password': '$2b$12$/8qmlGHWJr4FtAWKy1pof.z6zkedjEQQbKkNROsa8X8.5p4gHqHMK'},
               'CSANCHEZO': {'name': 'FGR SIS DE COLOMBIA AJUSTADORES DE SEGUROS SAS',
                             'password': '$2b$12$tq7DHitJBgD5yaKcywx3ieLaF4BLyYLJRqsaSaL6jKHvUF4dhWXGG'},
               'AAMORTEGUII': {'name': 'GENERAL CLAIMS AND RISK CONSULTING',
                               'password': '$2b$12$JRcO2raxGAUUg17ynHcfDOv77qY5bMLB8klbOAl7AIB1gzAICwjZ6'},
               'JROMEROA': {'name': 'HECTOR ROMERO Y ASOCIADOS LTDA',
                            'password': '$2b$12$0RRR0Sw1xGLXjFVFWgyFLezsvVjp8eqrqhp9wVuXMfYqsuqYcJwQm'},
               'CRAMIREZV': {'name': 'HUDSON SAS',
                             'password': '$2b$12$joUmT8QIbgsDmV9kYWC6tuq6NXzCT/LTJxEiAHBimvUD3tDDCoCyK'},
               'JMORAP': {'name': 'INGETECH COLOMBIAN GROUP SAS',
                          'password': '$2b$12$USUHrLLZx2vr4D2y9XzWze2ZCVB0CdDteNLZ6o8XZOV4fae.2YGUy'},
               'JCALDERONE': {'name': 'INNTERRA SAS',
                              'password': '$2b$12$iDSpa.1qLANJ01ibTEWmUudQeUz7kDsp1KBwJInhatsLTvNnQifKC'},
               'JRAMIREZA': {'name': 'Jara Ajustadores SAS',
                             'password': '$2b$12$lqvRrkYjcAFApiL48VZ.FuZ7x1f2mrdcH60xlcpifVx336LvH5VYG'},
               'JLURDUYA': {'name': 'JC LURDUY ASOCIADOS SAS',
                            'password': '$2b$12$R72bqClkI8YXJiUGCIeb7.HM9zNytExRVJ48jfLuRWWApFiUz9pxe'},
               'JFOREROR': {'name': 'JOSE ALEXANDER FORERO REINA',
                            'password': '$2b$12$cgwS2sIIthgbGb2NF/43PeppavjYVz18cEF4ddihVcaK5bd4Pdi5i'},
               'ARIOBO': {'name': 'MCLARENS COLOMBIA LIMITADA',
                          'password': '$2b$12$tsE5fy019kfj1DgQPyQJ1uaLuwaEOa9asJ6hd2LT4I2jP4n1..xGC'},
               'SMARTINEZG': {'name': 'MG LAWYER Y ADJUSTER S.A.S',
                              'password': '$2b$12$Ys6z6V.RuydklKdsvpzyqeZ1Ro3VlsapfJiCcVj1IPUJHLAVia.XG'},
               'HMONTOYAF': {'name': 'MONTOYA CARDENAS ABOGADOS S.A.S',
                             'password': '$2b$12$7YPFaI1AeZvSL2oz.un86Oo85fL/toGlLiDpypaSPI8oukx9kEzqW'},
               'BHERRERAA': {'name': 'Multiajustes SAS',
                             'password': '$2b$12$HKGUgjAgU9g53lWrCsy.lOtsDTOWn2aNR2/pa6xQggE/TmGxuti9.'},
               'IVARELAC': {'name': 'NISAN RISK SAS',
                            'password': '$2b$12$eGImshPgx.G7aptOtOXq0.JS9iTsiq0dvJH.4dby2MCdAcjS8cAhu'},
               'CNOGUERAC': {'name': 'ONC CONSULTING SAS',
                             'password': '$2b$12$BWKiiddwcHpIbut0c3VUtOD3fdtnjVOUlvUhM8tnvzbn/VVfJ56sq'},
               'OCASTANOL': {'name': 'OSCAR ALEJANDRO CASTAÑO LOPEZ',
                             'password': '$2b$12$9qjhLK2Caha4XtZJFxeZGOZrXqSnnIigARtP2xcGczcq1tI0oX3PG'},
               'PMESAM': {'name': 'Paulo Cesar Mesa Martinez',
                          'password': '$2b$12$GOmPjUOlxYJQR6cucpdX6enkd20Qu0gvFVv5QENCJWzZbUQAnvwEq'},
               'FSUAREZB': {'name': 'PROBIAJUSTES S.A.S',
                            'password': '$2b$12$LHVepkyD4xGQc91uwDS3Je75IOw1vJagZKw8iFwHsdYjLZP8WA1tK'},
               'ETAPIAG': {'name': 'PROSER AJUSTES SAS',
                           'password': '$2b$12$p3m9TdPdQ9y2V1XEHDc5OuUkquCQ0MyGqBANXeRsy5vYO4f38HpxS'},
               'DSANCHEZC': {'name': 'PROTECCION ASEGURADORES COLOMBIANOS S.A. PROASCOL S.A.',
                             'password': '$2b$12$oD1T5qIbzLLTrXv4V8VfDOC/Ooro0HMkRTZ3QpPDR6UCOu4wu99TS'},
               'JCANO': {'name': 'RYG ESPINOSA INTERNATIONAL ADJUSTER',
                         'password': '$2b$12$opHQwoFSd4pPqwjo27gI6uuzAV.S0JvjeaE7h3Jo5FlUaA4pa3gMC'},
               'JCAMARGOV': {'name': 'RCAID SAS',
                             'password': '$2b$12$aZy3y3U1aaGRIg.dM4vuvuIOGK/6ZR.H.F0zdl2JFr0K.eaRRymqy'},
               'LBAEZP': {'name': 'RIESGOS TASACIONES RTS COLOMBIA LTDA',
                          'password': '$2b$12$vOVKgfAzfcupfny2iSui9OHn33uUTi0/bnK2e20UXa87ScWsG8x62'},
               'LSALAMANCAC': {'name': 'S C SERVICIOS INTEGRALES DE LA SABANA SAS',
                               'password': '$2b$12$xPCgQvOX3RZkvloP1LGDPeK.d4rPgU78Ddl4651uGpI6hulDF5ec.'},
               'SVELEZM': {'name': 'SANTIAGO VELEZ MESA',
                           'password': '$2b$12$CGwXIw0v2IYcU9CYNBbYxuGWpdA3bziCAwJtLNfh8ZyUfn4xTSI8G'},
               'DTOBITOA': {'name': 'Sedgwick Colombia SAS',
                            'password': '$2b$12$bz1.W3WoPpI0S42.MeAMXeOHXShgHqcM.MVd.NTwvsKOgyhIfSAbG'},
               'SLOAIZA': {'name': 'SERGIO FERNANDO LOAIZA',
                           'password': '$2b$12$Y.xvwOoZYWBe//EqGyKjkOFqfypluOwEGld8Tum7icb9XhzfItezm'},
               'MARANGOM': {'name': 'SERVIAJUSTES S.A.S',
                            'password': '$2b$12$5WD.enBIfjlDU7LrXs3aXe99tuy2GHUVkk8EhQ8N0.UfoZoyR8Ccy'},
               'EMARTINEZM': {'name': 'SOGERISK ANDINA SAS',
                              'password': '$2b$12$0u1UbvtCtU9EUPYhpEJpOOGlrGyFi3dHmKEBhXCIp6UAV/TF7kTdG'},
               'YRODRIGUEZV': {'name': 'UNIVERSAL DE AJUSTES UNIAJUSTES Y C',
                               'password': '$2b$12$8eCa5IFNv.ihAdwtt9AdfeFnrMopirMHtlyz.E/Gotxi7lbEDAwb.'},
               'MRIZOP': {'name': 'UNIVERSAL INSURANCE SERVICES S.A.S',
                          'password': '$2b$12$9byc0V1Kqt9LsWdWyQnX8uP7K2FO3V7VTmCuBEx4kYkCAlc531w9m'},
               'IMORENO': {'name': 'VALUATIVE SAS',
                           'password': '$2b$12$dZnydANP7r50zdIiMLq.reuHpA3CN/6ISrTk1iwSTdaaaONNpA00.'},
               'YMEZAL': {'name': 'YAM INGENIERIA & CONSULTORIA SAS',
                          'password': '$2b$12$aVXAHE6WnWUxTRlIvo8.MOUy.AQNTBGYZWDeLmHt/nLiit/I.VNvi'},
               'YVICTORINOA': {'name': 'Yanko Victorino SAS',
                               'password': '$2b$12$B5Yc1N7PqfHJENXHHbrHtu0audNwnazhh.uXZXiyVkj3bw7l5BlOe'},
               'AZUNIGAR': {'name': 'Zúñiga Ajustadores SAS.',
                            'password': '$2b$12$jmBV8VQHdW2SAFCfyaG92esWVRb.oVtqMqA00YjQCRIlzl9mEXjw.'}}}
